// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTIFv-1ForI0i_omXsZnpn0PNQ_NcFZBY',
    appId: '1:41549679703:web:39f1d3bff786a73ba8a712',
    messagingSenderId: '41549679703',
    projectId: 'clone-bd2e6',
    authDomain: 'clone-bd2e6.firebaseapp.com',
    storageBucket: 'clone-bd2e6.appspot.com',
    measurementId: 'G-6TY8GX2XK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFEXzT7AinKmUfdlYcXgk4J2qIDJqAZIQ',
    appId: '1:41549679703:android:40ca9b6ffd4a1d90a8a712',
    messagingSenderId: '41549679703',
    projectId: 'clone-bd2e6',
    storageBucket: 'clone-bd2e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAliAEXqhXWMq8HkoNvnZKHBKNfPeEK7_g',
    appId: '1:41549679703:ios:8ced1789cc50e519a8a712',
    messagingSenderId: '41549679703',
    projectId: 'clone-bd2e6',
    storageBucket: 'clone-bd2e6.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAliAEXqhXWMq8HkoNvnZKHBKNfPeEK7_g',
    appId: '1:41549679703:ios:338c8d14e56bd8fda8a712',
    messagingSenderId: '41549679703',
    projectId: 'clone-bd2e6',
    storageBucket: 'clone-bd2e6.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
